
CREATE TABLE IF NOT EXISTS `{$prefix}order{$suffix}` (
  `orderid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ordersn` char(20) DEFAULT NULL COMMENT '订单编号',
  `wx_orderid` char(40) DEFAULT NULL COMMENT '微信订单号',
  `goods_id` int(10) unsigned NOT NULL COMMENT '产品id',
  `goods_num` int(10) unsigned DEFAULT '1' COMMENT '产品数量',
  `goods_name` varchar(255) NOT NULL COMMENT '产品名称',
  `goods_img` varchar(255) DEFAULT NULL COMMENT '图片地址',
  `amount` int(10) unsigned NOT NULL COMMENT '总额(以分为单位)',
  `price` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '单价(以分为单位)',
  `ship_price` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '运费(以分为单位)',
  `profit` int(11) NOT NULL DEFAULT '0' COMMENT '提成收益(以分为单位)',
  `sale_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '售销id',
  `sale_name` char(10) DEFAULT '' COMMENT '员工姓名',
  `sale_phone` char(15) DEFAULT '' COMMENT '销售电话',
  `sale_memo` varchar(255) DEFAULT NULL COMMENT '销售备注',
  `order_status` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '订单状态(1待支付,2已支付,3已发货,9已完成/已经签收,20已取消,30已失效)',
  `customer_id` int(10) unsigned DEFAULT '0' COMMENT '客户id',
  `customer_name` char(20) DEFAULT '' COMMENT '客户名称',
  `customer_openid` char(32) DEFAULT NULL COMMENT '客户微信开放id',
  `address` varchar(255) DEFAULT NULL COMMENT '客户地址',
  `mobile` char(15) DEFAULT NULL COMMENT '手机/电话',
  `customer_memo` varchar(255) DEFAULT NULL COMMENT '客户备注',
  `ship_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '物流id',
  `ship_name` char(10) NOT NULL DEFAULT '' COMMENT '物流名称',
  `ship_sn` char(20) NOT NULL DEFAULT '' COMMENT '运单号',
  `pay_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付时间',
  `complete_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '签收时间(完成时间)',
  `ship_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发货时间',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '数据状态, 1初始化，2=已更新, 3=已删除',
  `created` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  `deleted` int(10) NOT NULL DEFAULT '0' COMMENT '删除时间',
  PRIMARY KEY (`orderid`),
  UNIQUE KEY `ordersn` (`ordersn`),
  KEY `goods_id` (`goods_id`),
  KEY `sale_id` (`sale_id`),
  KEY `customer_id` (`customer_id`),
  KEY `status` (`status`),
  KEY `order_status` (`order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';

CREATE TABLE IF NOT EXISTS `{$prefix}order_log{$suffix}` (
  `logid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int(10) unsigned NOT NULL COMMENT '订单id',
  `old_status` tinyint(2) unsigned NOT NULL COMMENT '旧状态',
  `new_status` tinyint(2) unsigned NOT NULL COMMENT '新状态',
  `oper_id` int(10) unsigned NOT NULL COMMENT '操作人',
  `oper_name` char(20) DEFAULT NULL,
  `memo` varchar(255) NOT NULL COMMENT '原因',
  `status` tinyint(1) DEFAULT '1' COMMENT '数据状态, 1初始化，2=已更新, 3=已删除',
  `created` int(10) unsigned NOT NULL COMMENT '操作时间',
  `updated` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  `deleted` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '删除时间',
  PRIMARY KEY (`logid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单操作日志';
